In [1]:
import numpy as np

temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps > 30)

[False False False  True  True False False]


In [2]:
arr = np.random.randint(1, 10, (3, 4))
print(arr)

print(np.max(arr, axis=0))
print(np.min(arr, axis=1))

print(np.where(arr % 2, -1, arr))

[[1 7 2 3]
 [6 4 2 5]
 [4 9 1 1]]
[6 9 2 5]
[1 2 1]
[[-1 -1  2 -1]
 [ 6  4  2 -1]
 [ 4 -1 -1 -1]]


In [3]:
arr = np.arange(1, 13, 1)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)
print(np.sum(arr, axis=1))
print(np.mean(arr, axis=0))
print(np.reshape(arr, (12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr > 10])
# arr[arr > 10] = 0
# print(arr)
print(np.where(arr > 10, 0, arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [5]:
arr = np.array([120, 135, 110, 125, 130, 140])
print(np.sum(arr))
print(np.mean(arr).round(2))
print(np.var(arr).round(2))

print(np.argmax(arr) + 1)
print(np.argmin(arr)  +1)

760
126.67
97.22
6
3


In [6]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(np.concatenate((A, B)))
print(np.vstack((A, B))) # 纵向拼接
print(np.hstack((A, B))) # 横向拼接


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [7]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

[1 2 3 4]
[2 2 2 1]


In [8]:
arr1 = np.array([20, 25, 22, 30, 28])
arr2 = np.array([15, 18, 16, 22, 20])

arr3 = arr1 - arr2
print(arr3)

print(np.mean(arr3).round(2))
print(np.std(arr3).round(2))

# print(np.size(arr3[arr3 ==np.max(arr3)]))
print(np.where(arr3 == np.max(arr3)))

[5 7 6 8 8]
6.8
1.17
(array([3, 4]),)
