In [1]:
import numpy as np

### 切片

In [ ]:
# 一维数组的切片
arr = np.random.randint(1, 100, 20)
print(arr)

[17 39 62 80 79 83 84 16 98 54 73 79 61 93 95 78 60 21 61 57]


In [12]:
print(arr[3])
print(arr[2: 5])
print(arr[2: 15: 2])
print(arr[slice(2, 5)])
# 布尔切片
print(arr[arr > 50])


80
[62 80 79]
[62 79 84 98 73 61 95]
[62 80 79]
[62 80 79 83 84 98 54 73 79 61 93 95 78 60 61 57]


In [14]:
# 二维数组切片
arr = np.random.randint(1, 100, (4, 5))
print(arr)

[[67 54 27 57 12]
 [38 50 64 69 40]
 [20 72 77 37 40]
 [99 80 20 67 48]]


In [22]:
print(arr[1])
print(arr[1, 1: 3])
print(arr[1:])
# 布尔切片
print(arr[1][arr[1] > 50])

[38 50 64 69 40]
[50 64]
[[38 50 64 69 40]
 [20 72 77 37 40]
 [99 80 20 67 48]]
[64 69]


### ndarray运算

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** 2)
print(np.power(arr1, 2))

# 广播机制
# 两个矩阵在某个维度上的长度相同或者有一个的长度为1，则能进行广播
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([1, 2, 3])
'''
arr1:
1, 2, 3
4, 5, 6
7, 8, 9

arr2
1, 2, 3
1, 2 ,3
1, 2 ,3
'''
print(arr1 + arr2)

# 矩阵乘法
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[4, 5 ,6], [7, 8, 9], [1, 2, 3]])
print(arr1 @ arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
