In [1]:
import numpy as np

### 创建普通数组

In [2]:
arr = np.array([1, 2,3 ])
print(arr)

[1 2 3]


### 创建全空数组

In [3]:
arr = np.empty((2, 3), dtype=int)
print(arr)

[[2462380953976400430 8315165955255919981 4837492869154236742]
 [8318823007734488122 6658937522688187484 7022344665549521244]]


### 创建全0数组

In [4]:
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


### 创建全1数组

In [5]:
arr = np.ones((2, 3), dtype=int)
print(arr)
print(arr.dtype)
print(arr.shape)

[[1 1 1]
 [1 1 1]]
int64
(2, 3)


### 按照值填充


In [17]:
print(np.full((2, 3), 2))

[[2 2 2]
 [2 2 2]]


### 创建给定步长的数组

In [6]:
arr = np.arange(1, 11, 1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### 创建等间隔的数组

In [7]:
arr = np.linspace(1, 10, 4)
print(arr)

[ 1.  4.  7. 10.]


### 创建等比数列

In [8]:
arr = np.logspace(1, 10, 4, base=2)
print(arr)

[   2.   16.  128. 1024.]


### 特殊矩阵

In [ ]:
# 单位矩阵:主对角线上全为1，其余元素全为0
arr = np.eye(3)
print(arr)

# 对角矩阵：只有主对角线的元素不为0，其余元素全为0
print(np.diag([1, 3, 5]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


### 随机生成数组

In [10]:
# 随机生成(0,1)之间的浮点数
arr = np.random.rand(2, 3)
print(arr)

# 随机生成给定范围内的浮点数
arr = np.random.uniform(1, 10, (2, 3))
print(arr)

# 随机生成给定范围内的整数
arr = np.random.randint(1, 30, (2, 3))
print(arr)

# 随机生成正态分布的数
arr = np.random.randn(2, 3)
print(arr)

# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 20, (2, 3))
print(arr)

[[0.71211131 0.68349257 0.07126193]
 [0.45729649 0.84508809 0.66185752]]
[[1.31992122 6.95527246 3.53858209]
 [1.01167306 8.21384009 7.63359367]]
[[29 22 23]
 [20 11  6]]
[[-1.27732599 -1.48509769 -1.1861958 ]
 [ 0.06314983 -1.48095008  0.13449309]]
[[ 4 16 10]
 [12  8  3]]
