# Numpy特性
## 多维性
支持0维(标量) 1维(向量) 2维(矩阵)及更高维的数组

In [ ]:
import numpy as np

In [ ]:
arr = np.array(1) # 创建0维数组
print(arr)
print('arr的维度是: ', arr.ndim)

1
arr的维度是:  0


In [ ]:
arr = np.array([1, 2, 3]) # 创建一维数组
print(arr)
print('arr的维度是: ', arr.ndim)

[1 2 3]
arr的维度是:  1


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 创建二维数组
print(arr)
print('arr的维度是: ', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度是:  2


## 同质性
所有元素的类型必须保持一致

In [ ]:
arr = np.array([1, 'hello']) # 数据类型不同会强制转换
print(arr)

['1' 'hello']


## 高效性
基于连续内存块存储，支持向量化运算