# 常用函数
## 基本数学函数

In [2]:
import numpy as np

In [3]:
# 计算平方根
print(np.sqrt(9))

3.0


In [4]:
# 计算指数
print(np.exp(1)) # 以e为底
print(np.power(2, 3)) # 以2为底，求三次方
arr = np.array([1, 2, 3])
print(arr ** 2)
print(np.power(arr, 2))

2.718281828459045
8
[1 4 9]
[1 4 9]


In [5]:
# 计算自然对数
print(np.log(2.71)) # 以e为底

0.9969486348916096


In [6]:
# 三角函数
print(np.sin(np.pi / 2))
print(np.cos(0))
print(np.tan(0))

1.0
1.0
0.0


In [7]:
# 计算绝对值
arr = np.array([-1, -2, 3, 4])
print(np.abs(arr))

[1 2 3 4]


In [8]:
# 四舍五入
print(np.round([3.1, 3.5, 4.5]))

[3. 4. 4.]


In [9]:
# 向上取整
arr = np.array([1.5, 2.3, 25.4])
print(np.ceil(arr))
# 向下取整
print(np.floor(arr))

[ 2.  3. 26.]
[ 1.  2. 25.]


In [10]:
# 检测NaN
arr = np.array([1.3, 1.5, np.nan, 4])
np.isnan(arr)

array([False, False,  True, False])

## 统计函数
求和，平均值，中位数，标准差，方差，

最大值，最小值，最大值和最小值的差

计算分位数，累积和，累积积

In [11]:
# 求和
print(np.sum([1, 2, 3]))

# 平均值
print(np.mean([1, 2, 3]))

# 中位数
print(np.median([4, 1, 2]))

# 标准差
print(np.std([1, 2, 3]))

# 方差
print(np.var([1, 2, 3]))

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 最大值
print(np.max(arr)) # 整个数组最大值
print(np.max(arr, axis=0)) # 按列求最大值
print(np.max(arr, axis=1)) # 按行求最大值

# 最小值
print(np.min(arr)) # 整个数组最小值
print(np.min(arr, axis=0)) # 按列求最小值
print(np.min(arr, axis=1)) # 按行求最小值

# 最大最小差值
print(np.ptp(arr)) # 整个数组最大最小值的差值
print(np.ptp(arr, axis=0)) # 按列求最大最小值的差值
print(np.ptp(arr, axis=1)) # 按行求最大最小值的差值

# 分位数
print(np.percentile([1, 5, 10, 30], 50))

# 累积和
arr = np.array([1, 2, 3])
print(np.cumsum(arr))
# 累积积
print(np.cumprod(arr))

6
2.0
2.0
0.816496580927726
0.6666666666666666
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[7 8 9]
[3 6 9]
1
[1 2 3]
[1 4 7]
8
[6 6 6]
[2 2 2]
7.5
[1 3 6]
[1 2 6]


## 比较函数
判断是否大于，是否小于，是否等于

逻辑与，逻辑或，逻辑非

检查元素是否至少有一个为true，是否全部为true


In [12]:
# 大于
print(np.greater([1, 2, 3, 4, 5], 3))
# 小于
print(np.less([1, 2, 3, 4, 5], 3))
# 等于
print(np.equal([1, 2, 3, 4 ,5], 3))

# 逻辑与
print(np.logical_and([1, 0], [1, 1]))
# 逻辑或
print(np.logical_or([1, 0], [0, 1]))
# 逻辑非
print(np.logical_not([1, 0]))

#检查至少有一个为true
print(np.any([1, 1, 0, 0, 0]))
# 检查所有都为true
print(np.all([1, 1]))

[False False False  True  True]
[ True  True False False False]
[False False  True False False]
[ True False]
[ True  True]
[False  True]
True
True


In [13]:
# 自定义比较函数
#np.where(条件，符合值， 不符合值), 类似 ? : 三元运算符
#np.select(条件，取值)
arr = np.random.randint(50, 100, 10)
print(arr)

[83 99 95 90 92 82 79 92 83 74]


In [17]:
print(np.where(arr > 60, arr, 0))
print(np.where(arr > 60)) # 只有条件时，返回的是满足条件的索引
print(np.where(arr < 60, "不及格", np.where(
    arr >= 80, "优秀", "良好"
)))

print(np.select([arr < 60, (arr >= 60) & (arr < 80), arr >= 80], 
                ["不及格", "良好", "优秀"], default="未知"))

[ 0  0 65 68 68  0 84  0  0 88 71 89 89  0  0 66  0 88  0 89]
(array([ 2,  3,  4,  6,  9, 10, 11, 12, 15, 17, 19]),)
['不及格' '不及格' '良好' '良好' '良好' '不及格' '优秀' '不及格' '不及格' '优秀' '良好' '优秀' '优秀'
 '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '优秀']
['不及格' '不及格' '良好' '良好' '良好' '不及格' '优秀' '不及格' '不及格' '优秀' '良好' '优秀' '优秀'
 '不及格' '不及格' '良好' '不及格' '优秀' '不及格' '优秀']


In [ ]:
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)

# 排序
print(np.sort(arr))
# 输出排序后的对应索引
print(np.argsort(arr))

# 去重
u_arr, counts = np.unique(arr, return_counts=True) # return_counts = True表示返回每个元素出现次数
print(u_arr)
print(counts)

# 拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))

# 分割
print(np.split(arr, 4))

# 改变形状
print(np.reshape(arr, [4, 5]))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]
[1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 3]
[1 2 3 4 5 6]
[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32), array([71, 89, 89, 13, 59], dtype=int32), array([66, 40, 88, 47, 89], dtype=int32)]
[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
